name: app
description: Twitter-like sample app showing Clean Architecture with feature modules and feature toggles in Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.1
  firebase_crashlytics: ^5.0.1
  firebase_remote_config: ^6.0.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
